workflows:
  android_debug:
    name: Android Debug APK
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Show versions
        script: |
          java -version
          ./gradlew -v || true
      - name: Build Debug APK
        script: |
          chmod +x ./gradlew || true
          ./gradlew clean assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
