workflows:
  android_debug:
    name: Android Debug APK
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Build Debug APK
        script: |
          gradle clean assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
